# Generated by Django 4.2.2 on 2023-06-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='place',
            field=models.CharField(default='Earth', max_length=200),
            preserve_default=False,
        ),
    ]
